// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using W2contacts;

namespace W2contacts.Migrations
{
    [DbContext(typeof(ContactsContext))]
    partial class ContactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("W2contacts.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<int>("ConcessionariaID");

                    b.Property<string>("Email");

                    b.Property<string>("Estado");

                    b.Property<string>("NomeEmpresa");

                    b.Property<string>("NomeResponsavel");

                    b.Property<string>("RamoAtividade");

                    b.Property<string>("Telefone");

                    b.HasKey("ID");

                    b.HasIndex("ConcessionariaID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("W2contacts.Models.Concessionaria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContatoTecnico");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("ID");

                    b.ToTable("Concessionarias");
                });

            modelBuilder.Entity("W2contacts.Models.Cliente", b =>
                {
                    b.HasOne("W2contacts.Models.Concessionaria", "Concessionaria")
                        .WithMany("Clientes")
                        .HasForeignKey("ConcessionariaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
